CREATE TABLE ligue(
ID_LIGUE INT AUTO_INCREMENT,
NOM_LIGUE VARCHAR(255) NOT NULL,
ADMIN_LIGUE INT UNIQUE,
PRIMARY KEY (ID_LIGUE),
FOREIGN KEY (ADMIN_LIGUE) REFERENCES employe(ID_EMPLOYE)
);

CREATE TABLE employe(
ID_EMPLOYE INT AUTO_INCREMENT,
NOM_EMPLOYE VARCHAR(70) NOT NULL,
PRENOM_EMPLOYE VARCHAR(70),
MAIL_EMPLOYE VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
DATE_ARRIVE TIMESTAMP NOT NULL,
DATE_DEPART TIMESTAMP,
EST_ROOT BOOLEAN,
ID_LIGUE INT,
PRIMARY KEY (ID_EMPLOYE),
FOREIGN KEY (ID_LIGUE) REFERENCES ligue(ID_LIGUE)
);
